name: Atualizar lista M3U

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalar dependência
        run: pip install requests

      - name: Filtrar lista
        run: python filter.py

            - name: Salvar lista atualizada
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add lista.m3u
          git diff --cached --quiet || git commit -m "Atualizar lista M3U"
          git pull --rebase origin main
          git push
